# Sistemas Lineares

Um conjunto finito de equações lineares nas variáveis $x_{1}$, $x_{2}$, ..., $x_{n}$ é chamado um **sistema de equações lineares** ou um **sistema linear**. Uma sequência de números $s_{1}$, $s_{2}$, ..., $s_{n}$ é chamado uma **solução do sistema** se $x_{1}$ = $s_{1}$, $x_{2} = s_{2}$, ..., $x_{n}$ = $s_{n}$ é uma solução de cada equação do sistema. Todo sistema de equações lineares tem ou nenhuma solução, ou exatamente uma, ou então uma infinidade de soluções.

Vamos seguir os seguintes passos para encontrar o conjunto solução desse sistema linear, ou pelo menos uma das soluções dependendo da matriz apresentada.

$$AX = B$$

$$A.A^{-1}.X = A^{-1}.B$$

$$X = A^{-1}.B$$

In [4]:
!python -m pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -------- ------------------------------- 2.6/12.6 MB 15.7 MB/s eta 0:00:01
   ------------------------- -------------- 8.1/12.6 MB 21.8 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 22.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 19.9 MB/s eta 0:00:00


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [5]:
import numpy as np
from numpy.linalg import inv

A = np.array([[1,1],
             [-3,1]])
B = np.array([[6], [2]])

# Inversa de A
A_inversa = inv(A)
print(A)
print(A_inversa)

# Multiplicação entre matrizes utiliza dot

X = np.dot(A_inversa, B)
print(X)


[[ 1  1]
 [-3  1]]
[[ 0.25 -0.25]
 [ 0.75  0.25]]
[[1.]
 [5.]]
